name: Continuous Integration (CI)

on:
  push:
    branches: [ main, master ]

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/grzpra26/Eksperimen_SML_Grizzly.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        python --version
        pip --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    - name: Run mlflow project
      run: |
        echo "Menjalankan eksperimen MLflow..."
        mlflow run MLProject/ --env-manager local --experiment-name "Diabetes_Classification_Grizzly"

    - name: Get latest MLflow run_id
      id: get-run-id
      run: |
        RUN_ID=$(python -c "import mlflow; client = mlflow.tracking.MlflowClient(); runs = client.search_runs(client.get_experiment_by_name('Diabetes_Classification_Grizzly').experiment_id, order_by=['start_time DESC'], max_results=1); print(runs[0].info.run_id if runs else '')")
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Ditemukan Run ID: $RUN_ID"

    - name: Build Docker Image
      run: |
        echo "Membangun Docker image menggunakan mlflow models build-docker..."
        mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest" --enable-mlflow

    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-model-artifact
        path: |
          MLProject/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest
